#!/bin/bash

timestamp="$(date +%s)"
fname="/tmp/jot-${timestamp}"

if [ $# -gt 0 ]; then
    for word in $@ ; do
        title="${title}-${word}"
    done
    fname="${fname}${title}"
fi

fname="${fname}.txt"

cmd=${EDITOR:-${VISUAL:-nano}}
"${cmd}" "${fname}"

if [ -e "${fname}" ]; then
    printf "Saved to ${fname}\n"
else
    printf "Nothing written\n"
fi
